stylesheets: Fix undefined variable and mixin errors
- Before these changes, `bundle exec middleman build` failed with the following:

```
Error: Undefined variable: "$helvetica".
        on line 2:30 of source/assets/stylesheets/base/_variables.scss
        from line 6:9 of source/assets/stylesheets/base/_base.scss
        from line 4:9 of source/assets/stylesheets/application.css.scss
>> $base-font-family: "Roboto", $helvetica, sans-serif;

Error: no mixin named transition
        on line 4:12 of source/assets/stylesheets/base/_buttons.scss
        from line 11:9 of source/assets/stylesheets/base/_base.scss
        from line 4:9 of source/assets/stylesheets/application.css.scss
>>   @include transition(all 0.25s ease-in-out);

Error: Undefined variable: "$all-button-inputs".
        on line 1:3 of source/assets/stylesheets/base/_buttons.scss
        from line 11:9 of source/assets/stylesheets/base/_base.scss
        from line 4:9 of source/assets/stylesheets/application.css.scss
>> #{$all-button-inputs},
```

- The replacement for `$helvetica` comes from
  [here](https://github.com/thoughtbot/bourbon/blob/master/core/bourbon/library/_font-stacks.scss).
  Middleman uses Bourbon 7.0.0 these days.
- `$transition` was removed in 2015](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md#500alpha0---2015-08-21)
- `$all-button-inputs` was [replaced in 2016](https://github.com/thoughtbot/bourbon/pull/619).