stylesheets: Fix $height argument syntax in `size` mixin
```
Error: `80% 80%` is not a valid length for the `$height` argument in the `size` mixin.
        on line 40:5 of ../../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bourbon-7.0.0/core/bourbon/library/_size.scss, in mixin `size`
        from line 52:16 of source/assets/stylesheets/patterns/_vertical-tabs.scss, in mixin `@content`
        from line 88:7 of ../../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/neat-1.7.4/app/assets/stylesheets/grid/_media.scss, in mixin `media`
        from line 51:14 of source/assets/stylesheets/patterns/_vertical-tabs.scss
        from line 13:9 of source/assets/stylesheets/application.css.scss
>>     @error "`#{$height}` is not a valid length for the `$height` argument "
   ----^
```

- It turns out the arguments have to be comma-separated these days.